### PR TITLE
Code re-write to generate full set dividers

### PR DESCRIPTION
**Pull request by smithjw**

### CODE REVIEW

**Comment by davidfischer** [comment]
Did you decide to break this into a separate project? It was a little unclear exactly what the end product of this change was so it was kind of daunting to review.

**Comment by smithjw** [comment]
Sorry about this one David. I'd initially thought to open a PR against your original repo but given the large number of changes and how the fork was diverging, I opted to close and just continue work on my own copy.

My version of your original code is designed to generate full label cards that can be printed on thick paper/card stock to form an entire divider/label rather than printing and then sticking onto plastic/card dividers.

I really appreciate your initial repo as it gave me a great jumping off point.

I've also started initial work on a CSV import feature so that a user can export their MTG card collection from an app like [Lion's Eye (iOS)](https://apps.apple.com/au/app/mtg-scanner-lions-eye/id1546754798) or [Moxfield (web)](https://www.moxfield.com/users/smithjw) and generate dividers automatically (including color pip dividers for larger collections).

image

image

**Comment by davidfischer** [comment]
That's pretty sweet. In case anybody else wants something like that, the repo is here: https://github.com/smithjw/mtg-printable-set-label-generator

**Comment by smithjw** [comment]
I think the next step is to take a similar jump that you did and also have a web front-end to lower the barrier to entry ☺️

**Pull request closed without merging**
